xhost +SI:localuser:$USER >/dev/null
echo "DISPLAY=$DISPLAY"
echo "
Note: Xwayland fails if executed directly in compositor Sway.
In that case try:  x11docker --weston -- x11docker/xwayland" >&2
unset WAYLAND_DISPLAY
unset GDK_BACKEND QT_QPA_PLATFORM CLUTTER_BACKEND SDL_VIDEODRIVER ELM_DISPLAY ELM_ACCEL ECORE_EVAS_ENGINE
export XDG_SESSION_TYPE=x11
